### ISSUE TITLE
Handle parameters as plain arrays

### ISSUE THREAD

**Issue by IlyaOrson** [avik-pal/Lux.jl#50]
It would be useful to be able to handle the plain version of the parameters.
Otherwise it is necessary to keep track of the structure of a chain manually to reshape accordingly the plain parameters before evaluating a chain.

```julia
using Lux, Random, Optimisers, Zygote, ComponentArrays

# Seeding
rng = Random.default_rng()
Random.seed!(rng, 0)

# Construct the layer
model = Chain(BatchNorm(128), Dense(128, 256, tanh), BatchNorm(256),
              Chain(Dense(256, 1, tanh),Dense(1, 10)))

# Parameter and State Variables
ps, st = Lux.setup(rng, model)

# Dummy Input
x = rand(rng, Float32, 128, 2)

# Run the model
y, st = Lux.apply(model, x, ps, st)  # works

flat = ComponentArray(ps) |> collect
y, st = Lux.apply(model, x, flat, st)  # fails

ax = getaxes(ComponentArray(ps))
ps_new = ComponentArray(flat, ax)
y, st = Lux.apply(model, x, ps_new, st)  # works but feels like a workaround
```

**Comment by avik-pal** [comment]
There are quite a few reasons why I feel having a native abstract vector support for parameters is not ideal:

- The main issue with handling flat vectors is that we need to handle them separately for every layer. Note that we need to handle not just each base layer; for every Container Layer. Apart from the maintenance burden, this IMO makes the code extremely unreadable (rn we can access parameters like `ps.weight` and I know exactly what I am accessing, the proposed feature requires accessing values like `reshape(ps[1:l], ...)` which is pretty cryptic to look at)

- Broader Parameter Types without constraining how layers are implemented: Having an API where we can access the parameters with `.param_name` means any arbitrary data structure which allows indexing via getproperty is supported.

- Also I am not convinced by the example. The workaround is exactly the correct way of doing what you are asking and component arrays exist so that we don't have to handle flat vectors.

**Comment by IlyaOrson** [comment]
The current approach requires to look for the `getaxes` method and the particular constructor that builds the Component array from the flat version and the axes.
It is not bad but from a first time user perspective, it just felt like all the information for that was really contained implicitly in the Chain.

Since `Lux.setup` figures out the structure of the chain anyway, maybe a middle ground could be possible?
Maybe an explicit method that populates a parameter namedtuple with the chain's structure?

**Comment by avik-pal** [comment]
From https://lux.csail.mit.edu/dev/examples/generated/intermediate/BayesianNN/main/

```julia
function vector_to_parameters(ps_new::AbstractVector, ps::NamedTuple)
    @assert length(ps_new) == Lux.parameterlength(ps)
    i = 1
    function get_ps(x)
        z = reshape(view(ps_new, i:(i + length(x) - 1)), size(x))
        i += length(x)
        return z
    end
    return fmap(get_ps, ps)
end
```

**Comment by avik-pal** [comment]
This won't be supported. See https://github.com/avik-pal/Lux.jl/issues/50#issuecomment-1153309917 for details.
